name = "durable-objects-cron-test"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[durable_objects]
bindings = [
  { name = "CRON_DURABLE_OBJECT", class_name = "CronDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["CronDurableObject"]
